name: "Validate"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-black:
    name: With black
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check lint
        run: |
          black --check --diff --color --line-length=120 .

  validate-hassfest:
    name: With hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: With HACS action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
          comment: True


      # - uses: actions/setup-python@v5
      #   name: Setup Python

      # - uses: actions/cache@v2
      #   name: PIP Cache
      #   with:
      #     path: |
      #       ~/.cache/pip
      #     key: custom-component-ci

      # - uses: hacs/action@main
      #   name: HACS Validation
      #   with:
      #     CATEGORY: integration

      # - uses: home-assistant/actions/hassfest@master
      #   name: Hassfest Validation
